"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SEA = exports.Gun = void 0;
const min_1 = require("./min");
Object.defineProperty(exports, "Gun", { enumerable: true, get: function () { return min_1.Gun; } });
Object.defineProperty(exports, "SEA", { enumerable: true, get: function () { return min_1.SEA; } });
require("gun/lib/then");
require("gun/lib/radix");
require("gun/lib/radisk");
require("gun/lib/store");
require("gun/lib/rindexed");
require("gun/lib/webrtc");
